package mobileTest;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.LocalDateTime;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileBy;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class AndroidRobotDemo {

	@Test(enabled = true)
	public void emulator() {
		String deviceID = "4cf00ac"; // emulator-5554
		// String deviceID = "emulator-5554";

		AppiumDriver<MobileElement> driver = null;
		System.out.println("Check 1");
		// Set the Desired Capabilities
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "My Phone");
		caps.setCapability("udid", deviceID); // Give Device ID of your mobile phone
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "9.0");
		caps.setCapability("appPackage", "com.whatsapp");
		caps.setCapability("appActivity", "com.whatsapp.HomeActivity");
		caps.setCapability("noReset", true);

		// Instantiate Appium Driver
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:5000/wd/hub"), caps);

		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}

		// Added 5 seconds wait so that the app loads completely before starting with
		// element identification
		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		// Find Google Play element using ID property and click on it
		driver.findElementById("com.whatsapp:id/menuitem_search").click();

		// Find 'Google Play Store' element and set the value Google
		driver.findElement(By.id("com.whatsapp:id/search_src_text")).sendKeys("Vinisha");

		// driver.findElement(By.id("com.android.vending:id/search_box_text_input")).sendKeys(Keys.ENTER);
		// Press Enter key from Keyboard using any of the below methods
		((AndroidDriver<MobileElement>) driver).pressKeyCode(66);

		MobileElement item = scroll(driver, "Vinisha");
		item.click();

		WebDriverWait wait = new WebDriverWait(driver, 10);

		driver.findElementById("com.whatsapp:id/entry")
				.sendKeys("Hi, This message was generated by Manoj at: " + LocalDateTime.now().toString());
		driver.findElementById("com.whatsapp:id/send").click();

		// OR
		// The below code might now work for you, as some keyboards use Search button
		// instead of ENTER. Hence,
		// there are chances that the below line would fail on specific devices
		// driver.findElement(By.id("com.android.vending:id/search_box_text_input")).sendKeys(Keys.ENTER);
	}

	public MobileElement scroll(WebDriver driver, String text) {
		MobileElement element = (MobileElement) driver.findElement(MobileBy.AndroidUIAutomator(
				"new UiScrollable(new UiSelector().resourceId(\"com.whatsapp:id/data_view\")).scrollIntoView("
						+ "new UiSelector().textContains(\"" + text + "\").instance(0))"));
		return element;
	}

	@Test(enabled = false)
	public void device() {

		String deviceID = "emulator-5554"; // emulator-5554

		AppiumDriver<MobileElement> driver = null;

		// Set the Desired Capabilities
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "My Phone");
		caps.setCapability("udid", deviceID); // Give Device ID of your mobile phone
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "8.1");
		caps.setCapability("appPackage", "com.android.vending");
		caps.setCapability("appActivity", "com.google.android.finsky.activities.MainActivity");
		caps.setCapability("noReset", "true");

		// Instantiate Appium Driver
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:5000/wd/hub"), caps);

		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}

		// Added 5 seconds wait so that the app loads completely before starting with
		// element identification
		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		// Find Google Play element using ID property and click on it
		driver.findElement(By.id("com.android.vending:id/search_box_idle_text")).click();

		// Find 'Google Play Store' element and set the value Google
		driver.findElement(By.id("com.android.vending:id/search_box_text_input")).sendKeys("Test");
		// driver.findElement(By.id("com.android.vending:id/search_box_text_input")).sendKeys(Keys.ENTER);
		// Press Enter key from Keyboard using any of the below methods
		((AndroidDriver<MobileElement>) driver).pressKeyCode(66);
		// OR
		// The below code might now work for you, as some keyboards use Search button
		// instead of ENTER. Hence,
		// there are chances that the below line would fail on specific devices
		// driver.findElement(By.id("com.android.vending:id/search_box_text_input")).sendKeys(Keys.ENTER);
	}
}
